config/routes.rb
Rails.application.routes.draw do
  root 'financial_products#index'

  get '/login', to: 'sessions#login'

  
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  resources :sessions, only: [:create, :destroy] 

  resources :users, only: [:new, :create]

  resources :customers, except: [:new, :index] do
    resources :user_accounts, only: [:index, :new, :create]
  end

  resources :admins, except: [:new, :index] do
    get 'financial_stats', on: :collection
  end

  resources :user_accounts, only: [:show, :destroy], shallow: true  do
    resources :equities, controller: :positions, type: 'Equity'
  end

  resources :cash, controller: :positions, type: 'Cash', only: [:show, :edit, :update]

  resources :financial_products, only: :index do
    get 'acct_type_count', on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
    belongs_to :user_account

    scope :user_account_balance, -> (user_account) { where(user_account: user_account).sum(:value) }
    scope :index_by_user_account, -> (user_account) { joins(:user_account).where(user_account: user_account) }

    def transaction(transaction: , cash_amount: 0, shares: 0)
        
        case transaction

        when "Deposit"
            self.value += cash_amount
            "Deposited $#{cash_amount} in your account"

        when "Withdrawl"
            if self.value > cash_amount
                self.value -= cash_amount
                "$#{cash_amount} withdrawn from your account"
            else
                "Withdrawl canceled: Insuffcient funds"
            end

        when "Add"
            if self.affordable?(self.symbol, shares)
                self.update(shares: self.shares + shares)
                "#{shares} share(s) have been added to your position"
            else
                 "Insufficient Funds"
            end
              
        else
            if self.shares > shares
                self.update(shares: self.shares - shares)
                user_account.get_paid(self.total_purchase_price(self.symbol, shares))
                "You have sold #{shares} share(s)"
            else
                "Sell canceled: You cannot sell more than you have (#{self.shares})"
            end
        end
    end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController

    before_action :check_customer_user_account, only: [:index, :new, :create]
    before_action :check_customer_positions, except: [:index, :new, :create]

    def index
        @user_account = UserAccount.find_by(id: params[:user_account_id])
        @positions = Position.index_by_user_account(@user_account)
    end

    def new
        @equity = Equity.new(user_account_id: params[:user_account_id])
        @user_account = @equity.user_account
    end

    def create
        symbol, shares = params[:equity][:symbol].upcase, params[:equity][:shares].to_i
        @user_account = UserAccount.find_by(id: params[:user_account_id])
        return create_position_or_redirect_if_purchase_not_valid(symbol, shares)   
    end

    def show
        @position = Position.find_by(id: params[:id])
    end

    def edit
        @position = Position.find_by(id: params[:id])
        redirect_to customer_path(current_user), alert: "Position does not exist" if @position.nil?
    end

    def update
        @position = Position.find_by(id: params[:id])
        redirect_to customer_path(current_user) if @position.nil?
        params[:cash] ? cash_amount = params[:cash][:value].to_f : shares = params[:equity][:shares].to_i
        flash[:notice] = @position.transaction(transaction: params[:transaction], cash_amount: cash_amount, shares: shares)
        @position.save if params[:cash]
        redirect_to @position
    end

    def destroy
        @equity = Equity.find_by(id: params[:id])
        user_account = @equity.cash_from_sell
        @equity.destroy
        redirect_to user_account, notice: "Sell Complete"
    end

    private

    def check_customer_positions
        not_authorization unless current_user.positions.exists?(id: params[:id])
    end

    def check_customer_user_account
        not_authorization unless UserAccount.index_by_customer(current_user).exists?(id: params[:user_account_id]) 
    end

    def position_params
        params.require(:position).permit(:symbol, :shares, :user_account_id, :type, :value)
    end

    def equity_params
        params.require(:equity).permit(:symbol, :shares, :type)
    end

    def redirect_if_symbol_not_found(symbol)
        begin
            equity = Equity.lookup(symbol)
        rescue IEX::Errors::SymbolNotFoundError
            "This symbol not found"
        end
    end

    def create_position_or_redirect_if_purchase_not_valid(symbol, shares)
        res = redirect_if_symbol_not_found(symbol)
        return (redirect_to new_user_account_equity_path(@user_account), alert: res) if res.is_a?(String)
        @equity = @user_account.positions.build(equity_params)
        if @equity.save
            if @equity.affordable?(symbol, shares)
                redirect_to equity_path(@equity), notice: "You purchased #{shares} share(s) of #{symbol} for $#{@equity.total_purchase_price(symbol, shares)}"
            else
                @equity.destroy
                redirect_to new_user_account_equity_path(@user_account), alert: "Insufficient Funds"
            end
        else
            render :new
        end
    end
    
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_cash.html.erb
    <div class="text-center">
        <h1 class="jumbotron">Cash Position</h1>
        <h4><%= number_to_currency(cash.value) %></h4> <br>
    </div>
    

app/views/positions/_equity.html.erb

<div class="jumbotron text-center">
    <h1><%= equity.company_name(equity.symbol) %></h1>
    <h4><%= link_to 'add or reduce position', edit_equity_path(equity) %></h4> <br>
    <%= button_to 'Close Position', equity_path(equity), class: "btn btn-primary",method: :delete %>
</div> <br>

<table class="table table-borderless text-center">
    <thead>
        <tr>
            <th><h2>Equity Symbol</h2></th>
            <th><h2>Shares Owned</h2></th>
            <th><h2>Current Value</h2></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= equity.symbol %></td> 
            <td><%= equity.shares %></td>
            <td><%= number_to_currency(equity.total_value(equity.symbol)) %></td>
        </tr>
    </tbody>
</table>
<br>

 

app/views/positions/edit.html.erb
<% if @position.type == 'Cash' %>
  <h1 class="jumbotron text-center">Deposit/Withdrawl</h1>
<% else %>
  <h1 class="jumbotron text-center">Add/Reduce</h1>
<% end %>

<div class="text-center">
  <%= form_with model: @position do |f| %>
  
      <% if @position.type == 'Cash' %>
          <h2>Select type of transaction:</h2><br>
          <%= select_tag(:transaction, options_for_select([["Deposit", "Deposit"], ["Withdrawl", "Withdrawl"]])) %> <br><br>
          <%= f.number_field :value, value: 0, step: :any, min: 0 %> <br><br>
      <% else %>
          <h2>You currently have <%= @position.shares %> share(s) of <%= @position.symbol %></h2>
          <h5>Would you like to add to or reduce your position </h5><br>
          <%= select_tag(:transaction, options_for_select([["Add", "Add"], ["Reduce", "Reduce"]])) %> <br><br><br>
          <h5><%= f.label :shares %></h5>
          <%= f.number_field :shares, value: 0, min: 0 %> <br> <br>
      <% end %>
  
      <%= f.submit class: "btn btn-primary" %> <br>
  <% end %>
</div>

app/views/positions/index.html.erb
<div class="jumbotron text-center">
    <h1><%= @user_account.financial_product.name %> Positions</h1>
    <%= link_to 'User account home', @user_account %> <br><br>
</div><br>

<div class="text-center">
    <% cash = @positions.find {|position| position.type == 'Cash'} %>
    <% equities = @positions.filter {|position| position.type == 'Equity'} %>

        <h2>Cash</h2>
        Cash balance: <%= number_to_currency(cash.value) %> <br> 
        <%= link_to 'make a cash deposit/withdrawl', edit_cash_path(cash) %> <br><br>
        <h2>Equities</h2>
        <% equities.each do |equity| %>
            <%= link_to equity.symbol, equity_path(equity) %> <br>
        <% end %>


 <br><br>
    <%= link_to 'create new equity position', new_user_account_equity_path(@user_account) %>

</div>

app/views/positions/new.html.erb
<%= render partial: 'error_messages/full_messages', locals: { model: @equity } %>

<h1 class="jumbotron text-center">Open New Equity Position</h1>
    <div class="text-center">
        <%= form_with model: [@user_account, @equity] do |f| %>

            <%= f.hidden_field :type, value: 'Equity' %>
            <h2><%= f.label :symbol %></h2>
            <%= f.text_field :symbol %> <br><br><br>
            <h2><%= f.label :shares %></h2>
            <%= f.number_field :shares, value: 0, min: 0, step: 1 %> <br><br><br>
            <%= f.submit class: "btn btn-primary" %> <br>


        <% end %>
        <br>
    </div>
<%= link_to 'Back to Your Positions', user_account_equities_path(@user_account) %>


app/views/positions/show.html.erb


<% if @position.type == 'Equity' %>
  <%= render partial: "equity", locals: { equity: @position } %>
<% else %>
    <%= render partial: "cash", locals: { cash: @position } %>
<% end %>
<br><br><br><br><%= link_to 'Back to Your Positions', user_account_equities_path(@position.user_account) %>