config/routes.rb
Rails.application.routes.draw do
  root 'financial_products#index'

  get '/login', to: 'sessions#login'

  
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  resources :sessions, only: [:create, :destroy] 

  resources :users, only: [:new, :create]

  resources :customers, except: [:new, :index] do
    resources :user_accounts, only: [:index, :new, :create]
  end

  resources :admins, except: [:new, :index] do
    get 'financial_stats', on: :collection
  end

  resources :user_accounts, only: [:show, :destroy], shallow: true  do
    resources :equities, controller: :positions, type: 'Equity'
  end

  resources :cash, controller: :positions, type: 'Cash', only: [:show, :edit, :update]

  resources :financial_products, only: :index do
    get 'acct_type_count', on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center">
      <ul class="navbar-nav">
        <% if session[:user_id] %>
          <% if current_user.type == 'Customer' %>
            <li class="nav-item active"><%= link_to 'Home', customer_path(current_user), class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to 'Open New Account', new_customer_user_account_path(current_user), class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to 'View Your Accounts', customer_user_accounts_path(current_user), class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to 'Edit Profile', edit_customer_path(current_user), class: "nav-link" %></li>
            <li class="nav-item active"><%= button_to 'Close all Accounts and Delete Profile', customer_path(current_user), class: "nav-link btn", method: :delete %></li>
          <% else %>
            <li class="nav-item active"><%= link_to 'Home', admins_path(current_user), class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to 'Edit Profile', edit_admin_path(current_user), class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to 'Financial Statistics', financial_stats_admins_path, class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to 'Acct Type Count', acct_type_count_financial_products_path, class: "nav-link" %></li>
            <li class="nav-item active"><%= button_to 'Delete Account', admins_path(current_user), class: "nav-link btn", method: :delete %></li>
          <% end %>
            <li class="nav-item active"><%= button_to 'Log Out', session_path(current_user), class: "nav-link btn", method: :delete %> </li>
        <% else %>
          <li class="nav-item active"><%= button_to 'Log in with Github', '/auth/github', class: "nav-link btn", method: :post %></li>
          <li class="nav-item active"><%= link_to 'Log In', login_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to 'Sign Up', new_user_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </nav>
     <% flash.each do |name, msg| %>
       <%= content_tag :div, msg, class: "alert alert-success text-center" if name == 'notice' %>
       <%= content_tag :div, msg, class: "alert alert-danger text-center" if name == 'alert' %>
     <% end %>

    <%= yield %>

  </body>
</html>

app/views/layouts/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAmusementPark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>